# Generated by Django 2.2.2 on 2019-06-26 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('number_of_pages', models.IntegerField()),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('released_at', models.DateField(blank=True, null=True, verbose_name='Released Date')),
                ('authors', models.ManyToManyField(help_text='Select Authors for book', to='book.Author')),
                ('country', models.ForeignKey(help_text='Select Country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Country')),
                ('publisher', models.ForeignKey(help_text='Select publisher', null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Publisher')),
            ],
        ),
    ]
